"""Bias definitions for Tier 3 (B041–B060)."""

TIER3_BIASES = [
    {
        "bias_id": "B041",
        "name": "Actor-Observer Bias",
        "definition": "We explain other people's actions by their character, but our own by the situation.",
        "category": "Social Judgement",
        "description": "The same kind of behaviour gets different stories depending on whether we or someone else did it.",
        "everyday_tip": "When judging someone else, ask what situation might explain it — the way you would for yourself.",
        "common_contexts": "Work, Relationships, Driving, Everyday life",
        "tier": 3,
    },
    {
        "bias_id": "B042",
        "name": "Bias Blind Spot",
        "definition": "We notice biases in others more easily than in ourselves.",
        "category": "Self-awareness",
        "description": "It can feel obvious that other people are skewed, while our own view still feels objective.",
        "everyday_tip": "When you spot a bias in someone else, ask where the same pattern might show up in you.",
        "common_contexts": "Work, Relationships, Politics, Everyday life",
        "tier": 3,
    },
    {
        "bias_id": "B043",
        "name": "Naive Realism",
        "definition": "We believe we see reality directly and that reasonable people should agree with us.",
        "category": "Social Judgement",
        "description": "Our own perspective can feel like plain fact, making disagreement seem like bias or bad faith in others.",
        "everyday_tip": "When someone disagrees, ask what they might be seeing that you are not.",
        "common_contexts": "Politics, Work, Relationships, Media",
        "tier": 3,
    },
    {
        "bias_id": "B044",
        "name": "Just-World Hypothesis",
        "definition": "We assume people generally get what they deserve, and search for reasons bad outcomes were earned.",
        "category": "Social Judgement",
        "description": "The idea of a fair world can make us blame victims or downplay luck and circumstance.",
        "everyday_tip": "When something bad happens to someone, notice if you are looking for a reason they 'must have' deserved it.",
        "common_contexts": "Media, Relationships, Work, Politics",
        "tier": 3,
    },
    {
        "bias_id": "B045",
        "name": "Hostile Attribution Bias",
        "definition": "We interpret ambiguous actions from others as intentionally hostile or unkind.",
        "category": "Social Judgement",
        "description": "A neutral tone, delay, or mistake can be read as personal attack when the intent is unclear.",
        "everyday_tip": "Before assuming someone meant harm, ask what neutral explanation would also fit.",
        "common_contexts": "Relationships, Work, Everyday life, Social Media",
        "tier": 3,
    },
    {
        "bias_id": "B046",
        "name": "Egocentric Bias",
        "definition": "We remember our own role in events as larger and more central than it was.",
        "category": "Self-awareness",
        "description": "Our contribution, importance, or effort can loom larger in memory than in the shared reality.",
        "everyday_tip": "When recalling a group effort, ask what others would say they contributed.",
        "common_contexts": "Work, Relationships, Learning, Everyday life",
        "tier": 3,
    },
    {
        "bias_id": "B047",
        "name": "Illusion of Transparency",
        "definition": "We overestimate how clearly others can read our emotions and thoughts.",
        "category": "Social Judgement",
        "description": "What feels obvious inside can be nearly invisible outside, but we often assume people can tell.",
        "everyday_tip": "If something matters, say it plainly — do not assume your feelings are showing clearly.",
        "common_contexts": "Work, Relationships, Learning, Everyday life",
        "tier": 3,
    },
    {
        "bias_id": "B048",
        "name": "Hyperbolic Discounting",
        "definition": "We prefer smaller rewards now over larger rewards later, more steeply than calm planning would suggest.",
        "category": "Finance",
        "description": "The immediate option feels disproportionately attractive compared with a better long-term choice.",
        "everyday_tip": "Ask what future-you would prefer — not only what right-now-you wants.",
        "common_contexts": "Finance, Health, Everyday life, Work",
        "tier": 3,
    },
    {
        "bias_id": "B049",
        "name": "Ambiguity Effect",
        "definition": "We avoid options when the odds of a good outcome are unclear, even if they might be favourable.",
        "category": "Decision Making",
        "description": "Known risks can feel safer than unknown ones, so we may stick with the familiar gamble.",
        "everyday_tip": "When you avoid something because it feels uncertain, ask whether the known option is truly better.",
        "common_contexts": "Finance, Work, Health, Everyday life",
        "tier": 3,
    },
    {
        "bias_id": "B050",
        "name": "Identifiable Victim Effect",
        "definition": "We respond more strongly to one identifiable person in need than to large, statistical groups.",
        "category": "Emotion",
        "description": "A single story with a face and name can move us more than numbers describing many people.",
        "everyday_tip": "Notice when one story is pulling your attention away from the broader scale of a problem.",
        "common_contexts": "Media, Politics, Health, Everyday life",
        "tier": 3,
    },
    {
        "bias_id": "B051",
        "name": "Restraint Bias",
        "definition": "We overestimate our ability to resist temptation in the moment.",
        "category": "Self-awareness",
        "description": "We predict strong self-control in advance, then struggle when the temptation is actually in front of us.",
        "everyday_tip": "Plan for the moment of temptation, not the moment of planning.",
        "common_contexts": "Health, Everyday life, Finance, Work",
        "tier": 3,
    },
    {
        "bias_id": "B052",
        "name": "Reactance",
        "definition": "When we feel our freedom is threatened, we push back — sometimes by doing the opposite.",
        "category": "Emotion",
        "description": "Being told what to do can spark resistance, even when the advice is reasonable.",
        "everyday_tip": "Notice when you are saying no mainly because someone told you yes — or the reverse.",
        "common_contexts": "Relationships, Work, Health, Everyday life",
        "tier": 3,
    },
    {
        "bias_id": "B053",
        "name": "Ostrich Effect",
        "definition": "We avoid information that might force us to face an uncomfortable problem.",
        "category": "Finance",
        "description": "Not looking can feel like relief, even though the issue remains and may grow worse unseen.",
        "everyday_tip": "If you are avoiding a number, email, or conversation, ask what you are afraid it will confirm.",
        "common_contexts": "Finance, Health, Work, Relationships",
        "tier": 3,
    },
    {
        "bias_id": "B054",
        "name": "Zero-Sum Bias",
        "definition": "We treat situations as if one person's gain must mean another person's loss, even when both could benefit.",
        "category": "Social Judgement",
        "description": "Success, praise, or opportunity can feel like a fixed pie, making cooperation harder to see.",
        "everyday_tip": "When someone else wins, ask whether anything actually came off your plate.",
        "common_contexts": "Work, Relationships, Politics, Everyday life",
        "tier": 3,
    },
    {
        "bias_id": "B055",
        "name": "Moral Luck",
        "definition": "We judge the morality of an action partly by how lucky or unlucky the outcome was.",
        "category": "Social Judgement",
        "description": "The same choice can look wise or reckless depending on results that were not fully in the person's control.",
        "everyday_tip": "Try judging the decision separately from how lucky the outcome turned out to be.",
        "common_contexts": "Work, Driving, Relationships, Everyday life",
        "tier": 3,
    },
    {
        "bias_id": "B056",
        "name": "Texas Sharpshooter Fallacy",
        "definition": "We notice a cluster first, then draw a target around it as if we predicted it.",
        "category": "Decision Making",
        "description": "Patterns can be invented after the fact, making random data look meaningful.",
        "everyday_tip": "Ask whether you are finding a pattern because you looked for it — or because you predicted it beforehand.",
        "common_contexts": "Work, Media, Finance, Health",
        "tier": 3,
    },
    {
        "bias_id": "B057",
        "name": "Overconfidence Effect",
        "definition": "We are more certain of our judgments than our accuracy usually supports.",
        "category": "Self-awareness",
        "description": "Confidence can feel like proof, even when we are wrong surprisingly often.",
        "everyday_tip": "When you feel sure, ask what would make you only 70% sure instead of 100%.",
        "common_contexts": "Work, Learning, Finance, Everyday life",
        "tier": 3,
    },
    {
        "bias_id": "B058",
        "name": "Pro-Innovation Bias",
        "definition": "We assume a new tool or change will help more than it does, and overlook its limits.",
        "category": "Work",
        "description": "Novelty can feel like progress by itself, even before evidence shows it works better.",
        "everyday_tip": "Ask what problem the new thing solves — and what it might break.",
        "common_contexts": "Work, Health, Learning, Everyday life",
        "tier": 3,
    },
    {
        "bias_id": "B059",
        "name": "Semmelweis Reflex",
        "definition": "We reject new evidence or ideas because they challenge established norms or beliefs.",
        "category": "Learning",
        "description": "Familiar ways of doing things can feel safer than unfamiliar evidence, even when the evidence is strong.",
        "everyday_tip": "When a new idea feels wrong mainly because it is new, separate that feeling from whether it is actually wrong.",
        "common_contexts": "Work, Health, Learning, Politics",
        "tier": 3,
    },
    {
        "bias_id": "B060",
        "name": "Risk Compensation",
        "definition": "We take more risks when we feel safer, partly offsetting the protection we gained.",
        "category": "Health",
        "description": "Extra safety can lead to looser behaviour, so the overall risk may not fall as much as expected.",
        "everyday_tip": "When a safety measure makes you feel protected, ask whether you are relaxing in ways that bring risk back.",
        "common_contexts": "Health, Driving, Everyday life, Work",
        "tier": 3,
    },
]
