"""Challenge content for Tier 2 biases (C061–C120)."""

TIER2_CHALLENGES = [
    # B021 Planning Fallacy
    {
        "challenge_id": "C061", "bias_id": "B021", "bias": "Planning Fallacy",
        "statement": "I told myself the report would take an hour. Three hours later, I was still finishing tables.",
        "options": ("Recency Bias", "Planning Fallacy", "Optimism Bias", "Status Quo Bias"),
        "correct": "B", "explanation": "The estimate was far too optimistic compared with what actually happened.",
        "reflection": "What task recently took you much longer than you planned?",
        "why": "We picture the smooth version of a task and forget the delays, edits, and interruptions that usually show up.",
        "context": "Work", "difficulty": "Recognition",
        "objective": "Learn to compare new time estimates with how long similar tasks really took.",
    },
    {
        "challenge_id": "C062", "bias_id": "B021", "bias": "Planning Fallacy",
        "statement": "We left for the airport 'with plenty of time' — and still sprinted to the gate because packing took longer than expected.",
        "options": ("Normalcy Bias", "Planning Fallacy", "Anchoring Bias", "Recency Bias"),
        "correct": "B", "explanation": "Travel time was planned as if everything would go perfectly.",
        "reflection": "When travelling, do you build in buffer time or hope for the best?",
        "why": "A best-case mental movie feels realistic in advance, even when past trips told a different story.",
        "context": "Everyday life", "difficulty": "Application",
        "objective": "Learn that travel and prep tasks usually need margin, not ideal-case timing.",
    },
    {
        "challenge_id": "C063", "bias_id": "B021", "bias": "Planning Fallacy",
        "statement": "'I'll just tidy the kitchen before guests arrive' — then the whole evening slipped because small jobs kept appearing.",
        "options": ("Planning Fallacy", "Sunk Cost Fallacy", "Status Quo Bias", "Clustering Illusion"),
        "correct": "A", "explanation": "A quick job was treated as quick without room for the usual extras.",
        "reflection": "What 'small' job recently grew much bigger than you expected?",
        "why": "We estimate the main task and forget the side tasks that almost always come with it.",
        "context": "Everyday life", "difficulty": "Ambiguous",
        "objective": "Learn to notice when a simple task is being underestimated because hidden steps are ignored.",
    },
    # B022 Recency Bias
    {
        "challenge_id": "C064", "bias_id": "B022", "bias": "Recency Bias",
        "statement": "One bad week at work made me feel like I'm failing — even though the last six months went well.",
        "options": ("Negativity Bias", "Recency Bias", "Availability Heuristic", "Hindsight Bias"),
        "correct": "B", "explanation": "The latest week weighed more than the longer track record.",
        "reflection": "Has a recent rough patch ever overshadowed a longer stretch of good progress?",
        "why": "Fresh events are vivid and easy to recall, so they can feel like the whole story.",
        "context": "Work", "difficulty": "Recognition",
        "objective": "Learn to widen the time window before judging your overall performance.",
    },
    {
        "challenge_id": "C065", "bias_id": "B022", "bias": "Recency Bias",
        "statement": "After one great month of saving, I felt rich — and spent more, forgetting the tighter months before.",
        "options": ("Optimism Bias", "Recency Bias", "Loss Aversion", "Endowment Effect"),
        "correct": "B", "explanation": "The latest month shaped the feeling more than the fuller pattern.",
        "reflection": "Do recent wins or losses change your spending more than your average month?",
        "why": "What just happened feels most real right now, even when the longer pattern matters more.",
        "context": "Finance", "difficulty": "Application",
        "objective": "Learn to check your average pattern, not only your latest result.",
    },
    {
        "challenge_id": "C066", "bias_id": "B022", "bias": "Recency Bias",
        "statement": "My friend cancelled once last week, so I thought they were pulling away — though they'd been reliable for years.",
        "options": ("Fundamental Attribution Error", "Recency Bias", "Hostile Attribution Bias", "Negativity Bias"),
        "correct": "B", "explanation": "One recent event was treated as the new normal.",
        "reflection": "When did a single recent moment change how you saw someone overall?",
        "why": "The latest interaction is bright in memory and can drown out a longer history.",
        "context": "Relationships", "difficulty": "Ambiguous",
        "objective": "Learn to balance a recent event against the longer relationship pattern.",
    },
    # B023 Bandwagon Effect
    {
        "challenge_id": "C067", "bias_id": "B023", "bias": "Bandwagon Effect",
        "statement": "Everyone at work switched to a new app, so I did too — without checking if it actually helped me.",
        "options": ("Bandwagon Effect", "Authority Bias", "Status Quo Bias", "Mere Exposure Effect"),
        "correct": "A", "explanation": "Popularity became the reason to join in.",
        "reflection": "Have you adopted something mainly because others already had?",
        "why": "If many people are doing it, it can feel validated — even before we test it ourselves.",
        "context": "Work", "difficulty": "Recognition",
        "objective": "Learn to separate 'everyone is doing it' from 'this is right for me.'",
    },
    {
        "challenge_id": "C068", "bias_id": "B023", "bias": "Bandwagon Effect",
        "statement": "I bought the coat everyone was posting online — and only later wondered if I actually liked it.",
        "options": ("Halo Effect", "Confirmation Bias", "Bandwagon Effect", "Mere Exposure Effect"),
        "correct": "C", "explanation": "Trendiness pushed the choice more than personal preference.",
        "reflection": "Anything in your home that felt like a trend purchase afterward?",
        "why": "Seeing many people choose something makes it feel safer and more correct.",
        "context": "Social Media", "difficulty": "Application",
        "objective": "Learn to pause when popularity is doing most of the convincing.",
    },
    {
        "challenge_id": "C069", "bias_id": "B023", "bias": "Bandwagon Effect",
        "statement": "The whole group wanted the same restaurant, so I went along — even though I wanted something quieter.",
        "options": ("False Consensus Effect", "In-group Bias", "Bandwagon Effect", "Reactance"),
        "correct": "C", "explanation": "The group direction pulled the choice more than personal preference.",
        "reflection": "When did you follow the crowd even though you wanted something different?",
        "why": "Going with the group reduces friction and can feel like the obvious move.",
        "context": "Everyday life", "difficulty": "Ambiguous",
        "objective": "Learn to notice when group momentum is replacing your own preference.",
    },
    # B024 Mere Exposure Effect
    {
        "challenge_id": "C070", "bias_id": "B024", "bias": "Mere Exposure Effect",
        "statement": "A song I initially skipped started feeling good after the café played it every day.",
        "options": ("Mere Exposure Effect", "Bandwagon Effect", "Confirmation Bias", "Halo Effect"),
        "correct": "A", "explanation": "Repeated exposure created liking without any new reason.",
        "reflection": "Something you disliked at first but warmed to just from hearing or seeing it often?",
        "why": "Familiarity feels comfortable, and comfort can be mistaken for quality.",
        "context": "Everyday life", "difficulty": "Recognition",
        "objective": "Learn that liking can grow from repetition alone.",
    },
    {
        "challenge_id": "C071", "bias_id": "B024", "bias": "Mere Exposure Effect",
        "statement": "The new colleague seemed awkward at first — then likeable after a few lunches together.",
        "options": ("Halo Effect", "Mere Exposure Effect", "In-group Bias", "False Consensus Effect"),
        "correct": "B", "explanation": "Familiar contact warmed the impression over time.",
        "reflection": "Someone who grew on you mainly because you saw them more often?",
        "why": "Repeated contact lowers uncertainty and makes people feel easier to be around.",
        "context": "Work", "difficulty": "Application",
        "objective": "Learn to notice when familiarity is improving your opinion more than new information is.",
    },
    {
        "challenge_id": "C072", "bias_id": "B024", "bias": "Mere Exposure Effect",
        "statement": "I chose the logo design we'd seen in every mock-up — not because it was best, but because it felt right.",
        "options": ("Status Quo Bias", "Choice-Supportive Bias", "Mere Exposure Effect", "Anchoring Bias"),
        "correct": "C", "explanation": "Repeated viewing made one option feel more natural.",
        "reflection": "Have you preferred the version you saw most often, not the one you judged most carefully?",
        "why": "What we see repeatedly feels more true, safe, and 'ours.'",
        "context": "Work", "difficulty": "Ambiguous",
        "objective": "Learn to separate repeated exposure from genuine preference.",
    },
    # B025 Endowment Effect
    {
        "challenge_id": "C073", "bias_id": "B025", "bias": "Endowment Effect",
        "statement": "I wouldn't pay £80 for that mug in a shop — but I also don't want to sell mine for £80.",
        "options": ("Sunk Cost Fallacy", "Endowment Effect", "Loss Aversion", "Anchoring Bias"),
        "correct": "B", "explanation": "Owning it made the same mug feel worth more.",
        "reflection": "Something you would not rebuy today but still do not want to let go?",
        "why": "Ownership attaches identity and memory, which inflates how valuable something feels.",
        "context": "Everyday life", "difficulty": "Recognition",
        "objective": "Learn that ownership alone can change what price feels fair.",
    },
    {
        "challenge_id": "C074", "bias_id": "B025", "bias": "Endowment Effect",
        "statement": "Selling my old bike felt painful, even though I had not ridden it in two years.",
        "options": ("Endowment Effect", "Sunk Cost Fallacy", "Status Quo Bias", "Loss Aversion"),
        "correct": "A", "explanation": "Letting go of something owned felt costly beyond its use.",
        "reflection": "Something you kept mainly because it was yours, not because you used it?",
        "why": "Giving up what we own can feel like losing part of ourselves, not just an object.",
        "context": "Finance", "difficulty": "Application",
        "objective": "Learn to ask what an item is worth to you now, not what ownership added emotionally.",
    },
    {
        "challenge_id": "C075", "bias_id": "B025", "bias": "Endowment Effect",
        "statement": "I priced my childhood books higher than identical copies online — because they had been on my shelf.",
        "options": ("Anchoring Bias", "Endowment Effect", "Choice-Supportive Bias", "Sunk Cost Fallacy"),
        "correct": "B", "explanation": "Personal ownership pushed the price above the market norm.",
        "reflection": "Have you overpriced something you were selling because it felt special to you?",
        "why": "Our things carry stories, and those stories can feel like extra market value.",
        "context": "Everyday life", "difficulty": "Ambiguous",
        "objective": "Learn to separate sentimental value from what a buyer would actually pay.",
    },
    # B026 Gambler's Fallacy
    {
        "challenge_id": "C076", "bias_id": "B026", "bias": "Gambler's Fallacy",
        "statement": "The coin landed heads four times, so tails felt 'due' on the next flip.",
        "options": ("Clustering Illusion", "Gambler's Fallacy", "Representativeness Heuristic", "Illusion of Control"),
        "correct": "B", "explanation": "Past flips do not change the odds of the next independent flip.",
        "reflection": "Have you ever expected luck to 'balance out' right away?",
        "why": "Random sequences can look like they owe us a correction, even when each event is fresh.",
        "context": "Everyday life", "difficulty": "Recognition",
        "objective": "Learn that independent random events do not repay earlier outcomes.",
    },
    {
        "challenge_id": "C077", "bias_id": "B026", "bias": "Gambler's Fallacy",
        "statement": "After three rainy weekends, I packed for sun — because it 'had to' change soon.",
        "options": ("Gambler's Fallacy", "Optimism Bias", "Normalcy Bias", "Recency Bias"),
        "correct": "A", "explanation": "Weather was treated as if it should balance a streak, not start fresh each week.",
        "reflection": "When have you expected a streak to end just because it had gone on long enough?",
        "why": "Streaks feel meaningful, but many natural patterns do not keep score for us.",
        "context": "Everyday life", "difficulty": "Application",
        "objective": "Learn to ask whether a streak actually changes the next odds.",
    },
    {
        "challenge_id": "C078", "bias_id": "B026", "bias": "Gambler's Fallacy",
        "statement": "Our team lost twice, so I felt the next match was almost guaranteed — as if losses had to be repaid.",
        "options": ("Optimism Bias", "Gambler's Fallacy", "Survivorship Bias", "Hindsight Bias"),
        "correct": "B", "explanation": "Past results were treated as if they forced a coming correction.",
        "reflection": "Have past results ever made you feel sure the next one would swing the other way?",
        "why": "We like stories where things even out, even when the next try is its own separate chance.",
        "context": "Sport", "difficulty": "Ambiguous",
        "objective": "Learn to treat the next attempt on its own merits, not as debt repayment from earlier results.",
    },
    # B027 Clustering Illusion
    {
        "challenge_id": "C079", "bias_id": "B027", "bias": "Clustering Illusion",
        "statement": "Three colleagues quit in one month, so I decided the company must be in trouble.",
        "options": ("Recency Bias", "Survivorship Bias", "Clustering Illusion", "Availability Heuristic"),
        "correct": "C", "explanation": "A short cluster was read as a meaningful signal from very little data.",
        "reflection": "A small streak that made you sure something bigger was going on?",
        "why": "Our brains are pattern hunters, and a few similar events can look like proof.",
        "context": "Work", "difficulty": "Recognition",
        "objective": "Learn to ask how much data you really have before calling something a trend.",
    },
    {
        "challenge_id": "C080", "bias_id": "B027", "bias": "Clustering Illusion",
        "statement": "Two buses arrived together, so I concluded the schedule was broken — though it might have been chance.",
        "options": ("Gambler's Fallacy", "Clustering Illusion", "Illusory Correlation", "Normalcy Bias"),
        "correct": "B", "explanation": "A clump in timing was treated as a system failure without enough evidence.",
        "reflection": "When have a few coincidences felt like a clear pattern to you?",
        "why": "Clusters stand out in memory, while ordinary spacing is easy to forget.",
        "context": "Everyday life", "difficulty": "Application",
        "objective": "Learn that clumps can happen by chance and still feel intentional.",
    },
    {
        "challenge_id": "C081", "bias_id": "B027", "bias": "Clustering Illusion",
        "statement": "Three friends got colds the same week, so I blamed the restaurant — with no real link.",
        "options": ("Illusory Correlation", "Base Rate Neglect", "Clustering Illusion", "Availability Heuristic"),
        "correct": "C", "explanation": "A short cluster was turned into a cause without checking how often that happens randomly.",
        "reflection": "A coincidence you turned into a story with a culprit?",
        "why": "When events bunch together, we often invent a tidy explanation instead of sitting with randomness.",
        "context": "Health", "difficulty": "Ambiguous",
        "objective": "Learn to test whether a cluster is large enough to mean anything.",
    },
    # B028 Representativeness Heuristic
    {
        "challenge_id": "C082", "bias_id": "B028", "bias": "Representativeness Heuristic",
        "statement": "Quiet, careful, loves reading — I guessed librarian, not salesperson, without checking the odds.",
        "options": ("Base Rate Neglect", "Representativeness Heuristic", "Conjunction Fallacy", "Availability Heuristic"),
        "correct": "B", "explanation": "The description fit a stereotype more than it fit real-world frequency.",
        "reflection": "When have you guessed someone's job or role from vibes alone?",
        "why": "A neat type-match feels convincing, even when the stereotype is rare in reality.",
        "context": "Everyday life", "difficulty": "Recognition",
        "objective": "Learn that a good fit to a stereotype is not the same as a good probability estimate.",
    },
    {
        "challenge_id": "C083", "bias_id": "B028", "bias": "Representativeness Heuristic",
        "statement": "The polished speaker seemed like a great analyst — though their numbers did not hold up.",
        "options": ("Halo Effect", "Representativeness Heuristic", "Authority Bias", "Confirmation Bias"),
        "correct": "B", "explanation": "They looked like the type of person who should be good at analysis.",
        "reflection": "When has someone 'seemed like' the right person for a role before you checked the work?",
        "why": "We use prototypes to judge skill, because prototypes are easier than evidence.",
        "context": "Work", "difficulty": "Application",
        "objective": "Learn to check performance instead of type-fit when judging competence.",
    },
    {
        "challenge_id": "C084", "bias_id": "B028", "bias": "Representativeness Heuristic",
        "statement": "A startup with a sleek office felt destined to succeed — more than a scrappy one with better sales.",
        "options": ("Halo Effect", "Survivorship Bias", "Representativeness Heuristic", "Optimism Bias"),
        "correct": "C", "explanation": "Success was inferred from how the company looked, not how it performed.",
        "reflection": "What surface cues have ever made something feel more successful than it was?",
        "why": "We expect success to look a certain way, so the look itself can sell the story.",
        "context": "Work", "difficulty": "Ambiguous",
        "objective": "Learn to separate appearance of success from actual results.",
    },
    # B029 Base Rate Neglect
    {
        "challenge_id": "C085", "bias_id": "B029", "bias": "Base Rate Neglect",
        "statement": "After one dramatic news story, I worried the problem was everywhere — though it is actually rare.",
        "options": ("Availability Heuristic", "Base Rate Neglect", "Negativity Bias", "Illusory Truth Effect"),
        "correct": "B", "explanation": "A vivid case overpowered how uncommon the issue really is.",
        "reflection": "A rare problem that felt common because one example was memorable?",
        "why": "Specific stories hit harder than background statistics, so the story can feel like the norm.",
        "context": "Media", "difficulty": "Recognition",
        "objective": "Learn to start with how common something is before judging from one example.",
    },
    {
        "challenge_id": "C086", "bias_id": "B029", "bias": "Base Rate Neglect",
        "statement": "The test came back positive, and I panicked — forgetting how often false positives happen in screening.",
        "options": ("Availability Heuristic", "Base Rate Neglect", "Negativity Bias", "Framing Effect"),
        "correct": "B", "explanation": "The result felt definitive without weighing how common false positives are.",
        "reflection": "When have you reacted to one result without the broader odds?",
        "why": "A single alarming number feels personal and urgent, while base rates feel abstract.",
        "context": "Health", "difficulty": "Application",
        "objective": "Learn to combine test results with how often they are wrong in your group.",
    },
    {
        "challenge_id": "C087", "bias_id": "B029", "bias": "Base Rate Neglect",
        "statement": "She matched the profile perfectly, so I was sure she was the right hire — though most strong profiles still fail.",
        "options": ("Representativeness Heuristic", "Halo Effect", "Base Rate Neglect", "Confirmation Bias"),
        "correct": "C", "explanation": "A good fit to the ideal profile ignored how few such candidates work out overall.",
        "reflection": "When have you felt certain from a great match without the bigger success rate?",
        "why": "A perfect-seeming case can make us forget how often similar cases do not pan out.",
        "context": "Work", "difficulty": "Ambiguous",
        "objective": "Learn to ask how often similar-looking cases succeed, not only how good this one looks.",
    },
    # B030 Peak-End Rule
    {
        "challenge_id": "C088", "bias_id": "B030", "bias": "Peak-End Rule",
        "statement": "The holiday was mostly fine, but one awful final day made me call the whole trip bad.",
        "options": ("Negativity Bias", "Peak-End Rule", "Recency Bias", "Choice-Supportive Bias"),
        "correct": "B", "explanation": "The ending reshaped memory more than the full week.",
        "reflection": "A trip or event remembered mainly by its worst moment or ending?",
        "why": "Peaks and endings are vivid, so they can rewrite how the whole experience feels.",
        "context": "Everyday life", "difficulty": "Recognition",
        "objective": "Learn that memory often weights the peak and ending more than the middle.",
    },
    {
        "challenge_id": "C089", "bias_id": "B030", "bias": "Peak-End Rule",
        "statement": "The dentist visit hurt most at the end, so I remembered it as painful — though most of it was fine.",
        "options": ("Negativity Bias", "Peak-End Rule", "Availability Heuristic", "Recency Bias"),
        "correct": "B", "explanation": "The final discomfort dominated the memory of the whole appointment.",
        "reflection": "An experience where the ending coloured the whole memory?",
        "why": "How something ends leaves a strong stamp on what we take away.",
        "context": "Health", "difficulty": "Application",
        "objective": "Learn to recall the full timeline, not only the loudest or last moment.",
    },
    {
        "challenge_id": "C090", "bias_id": "B030", "bias": "Peak-End Rule",
        "statement": "One amazing dessert at the end made me rave about a restaurant — even though the main course was average.",
        "options": ("Halo Effect", "Peak-End Rule", "Choice-Supportive Bias", "Mere Exposure Effect"),
        "correct": "B", "explanation": "A strong ending lifted the whole meal in memory.",
        "reflection": "Has a great ending ever made you recommend something more than the full experience deserved?",
        "why": "A high point at the close can make the whole episode feel better than it was minute by minute.",
        "context": "Everyday life", "difficulty": "Ambiguous",
        "objective": "Learn to judge experiences across the whole arc, not only the highlight or finish.",
    },
]
