"""Challenge content for Tier 3 biases B051–B060 (C151–C180)."""

TIER3_CHALLENGES_B = [
    # B051 Restraint Bias
    {
        "challenge_id": "C151", "bias_id": "B051", "bias": "Restraint Bias",
        "statement": "I bought one biscuit for later and said I'd stop at one — I ate four once I opened the pack.",
        "options": ("Hyperbolic Discounting", "Restraint Bias", "Planning Fallacy", "Optimism Bias"),
        "correct": "B", "explanation": "Future self-control was overestimated before temptation arrived.",
        "reflection": "A 'just one' promise that collapsed once the thing was in front of you?",
        "why": "In advance, resisting feels easy because the craving is not here yet.",
        "context": "Health", "difficulty": "Recognition",
        "objective": "Learn to plan for the moment of temptation, not the moment of planning.",
    },
    {
        "challenge_id": "C152", "bias_id": "B051", "bias": "Restraint Bias",
        "statement": "I told myself I'd only check my phone once during dinner — and picked it up every few minutes.",
        "options": ("Restraint Bias", "Hyperbolic Discounting", "Illusion of Control", "Status Quo Bias"),
        "correct": "A", "explanation": "I predicted stronger restraint than I actually had in the moment.",
        "reflection": "A limit you set for yourself that you broke almost immediately?",
        "why": "We picture our disciplined self without the pull of the actual trigger in front of us.",
        "context": "Everyday life", "difficulty": "Application",
        "objective": "Learn to make temptation harder to reach instead of trusting willpower alone.",
    },
    {
        "challenge_id": "C153", "bias_id": "B051", "bias": "Restraint Bias",
        "statement": "Before the party I said I wouldn't drink much — by midnight I'd lost count.",
        "options": ("Optimism Bias", "Restraint Bias", "Bandwagon Effect", "Hyperbolic Discounting"),
        "correct": "B", "explanation": "Self-control looked stronger on the way in than it was in the room.",
        "reflection": "Social plans where you were more confident beforehand than you turned out to be?",
        "why": "Social mood and cues are hard to simulate in advance, so restraint gets overbooked.",
        "context": "Everyday life", "difficulty": "Ambiguous",
        "objective": "Learn to set guardrails before environments that weaken your restraint.",
    },
    # B052 Reactance
    {
        "challenge_id": "C154", "bias_id": "B052", "bias": "Reactance",
        "statement": "The moment my parent told me to tidy up, I wanted to do it less — even though I had planned to.",
        "options": ("Reactance", "Status Quo Bias", "Self-serving Bias", "In-group Bias"),
        "correct": "A", "explanation": "Being told what to do sparked resistance instead of cooperation.",
        "reflection": "Something you resisted mainly because someone ordered you to do it?",
        "why": "When freedom feels threatened, pushing back can feel more urgent than the task itself.",
        "context": "Relationships", "difficulty": "Recognition",
        "objective": "Learn to notice when resistance is about autonomy, not the actual request.",
    },
    {
        "challenge_id": "C155", "bias_id": "B052", "bias": "Reactance",
        "statement": "A 'limited time only' message made me want the deal more — mostly because I hated being pushed.",
        "options": ("Loss Aversion", "Reactance", "Bandwagon Effect", "Anchoring Bias"),
        "correct": "B", "explanation": "Pressure to act quickly triggered pushback disguised as desire.",
        "reflection": "A sales tactic that made you want to say no on principle?",
        "why": "Hard sells can feel like someone is grabbing the steering wheel, and we grab back.",
        "context": "Everyday life", "difficulty": "Application",
        "objective": "Learn to separate whether you want something from whether you resent being nudged.",
    },
    {
        "challenge_id": "C156", "bias_id": "B052", "bias": "Reactance",
        "statement": "My manager said I had to use the new form, so I dragged my feet — even though it might help.",
        "options": ("Status Quo Bias", "Reactance", "Semmelweis Reflex", "Pro-Innovation Bias"),
        "correct": "B", "explanation": "Mandatory change sparked resistance more than the form itself did.",
        "reflection": "A reasonable change you resisted because it was imposed, not proposed?",
        "why": "Choice matters to us, so commands can make decent ideas feel like battles.",
        "context": "Work", "difficulty": "Ambiguous",
        "objective": "Learn to judge the change on its merits, not only on how much freedom you felt you lost.",
    },
    # B053 Ostrich Effect
    {
        "challenge_id": "C157", "bias_id": "B053", "bias": "Ostrich Effect",
        "statement": "I haven't opened my credit card app in weeks — the balance makes me tense.",
        "options": ("Loss Aversion", "Ostrich Effect", "Normalcy Bias", "Sunk Cost Fallacy"),
        "correct": "B", "explanation": "Avoiding the information felt easier than facing the problem.",
        "reflection": "A bill, email, or number you have been putting off looking at?",
        "why": "Not looking can briefly protect us from bad feelings, even when it leaves the issue untouched.",
        "context": "Finance", "difficulty": "Recognition",
        "objective": "Learn that avoiding information rarely makes the underlying problem smaller.",
    },
    {
        "challenge_id": "C158", "bias_id": "B053", "bias": "Ostrich Effect",
        "statement": "My knee has been sore for months, but I keep postponing the doctor because I don't want bad news.",
        "options": ("Optimism Bias", "Ostrich Effect", "Normalcy Bias", "Restraint Bias"),
        "correct": "B", "explanation": "Fear of confirmation led to delaying the check entirely.",
        "reflection": "A health worry you have avoided investigating because you hoped it would go away?",
        "why": "Possible bad news can feel safer as a vague worry than as a confirmed fact.",
        "context": "Health", "difficulty": "Application",
        "objective": "Learn to face uncomfortable information early, when you still have more options.",
    },
    {
        "challenge_id": "C159", "bias_id": "B053", "bias": "Ostrich Effect",
        "statement": "I saw the project was slipping but avoided the status meeting — hoping it would sort itself out.",
        "options": ("Optimism Bias", "Ostrich Effect", "Planning Fallacy", "Status Quo Bias"),
        "correct": "B", "explanation": "I stepped away from information that would force a hard conversation.",
        "reflection": "A problem at work you dodged because looking closely would make it real?",
        "why": "Meetings and updates can turn worry into action, and action can feel heavier than hope.",
        "context": "Work", "difficulty": "Ambiguous",
        "objective": "Learn to seek the update you are avoiding when you already suspect trouble.",
    },
    # B054 Zero-Sum Bias
    {
        "challenge_id": "C160", "bias_id": "B054", "bias": "Zero-Sum Bias",
        "statement": "When my friend got promoted, part of me felt like that meant less chance for me.",
        "options": ("In-group Bias", "Zero-Sum Bias", "Loss Aversion", "Survivorship Bias"),
        "correct": "B", "explanation": "Their gain was treated as my loss, even though both could succeed.",
        "reflection": "Someone else's win that felt like it shrunk your opportunity?",
        "why": "Success can feel like a fixed pie, especially when we are competing for attention or roles.",
        "context": "Work", "difficulty": "Recognition",
        "objective": "Learn to ask whether another person's gain actually reduces yours.",
    },
    {
        "challenge_id": "C161", "bias_id": "B054", "bias": "Zero-Sum Bias",
        "statement": "If the other team gets more budget, I assume ours has to lose out — even in a growing company.",
        "options": ("Zero-Sum Bias", "Framing Effect", "Loss Aversion", "Status Quo Bias"),
        "correct": "A", "explanation": "Resources were treated as strictly either-or.",
        "reflection": "A situation where more for them automatically felt like less for you?",
        "why": "Competition trains us to see wins as taking slices from the same pie.",
        "context": "Work", "difficulty": "Application",
        "objective": "Learn to look for growing or shared wins before assuming trade-offs.",
    },
    {
        "challenge_id": "C162", "bias_id": "B054", "bias": "Zero-Sum Bias",
        "statement": "My sibling's happy relationship somehow felt like a comment on mine — as if happiness were limited.",
        "options": ("Negativity Bias", "Zero-Sum Bias", "In-group Bias", "Self-serving Bias"),
        "correct": "B", "explanation": "Their good news was read as reducing what was available to me.",
        "reflection": "Someone else's good news that quietly felt threatening to you?",
        "why": "When we feel scarce in an area, other people's gains can feel like our losses.",
        "context": "Relationships", "difficulty": "Ambiguous",
        "objective": "Learn that many good outcomes can coexist without cancelling each other.",
    },
    # B055 Moral Luck
    {
        "challenge_id": "C163", "bias_id": "B055", "bias": "Moral Luck",
        "statement": "Two drivers rolled through the same stop sign — one got fined, one didn't. We called one reckless and one fine.",
        "options": ("Fundamental Attribution Error", "Moral Luck", "Hindsight Bias", "Just-World Hypothesis"),
        "correct": "B", "explanation": "The same choice got different moral labels because the outcomes differed.",
        "reflection": "When has luck changed how harshly you judged the same kind of choice?",
        "why": "Outcomes are vivid, so we often grade the decision by how lucky the ending was.",
        "context": "Driving", "difficulty": "Recognition",
        "objective": "Learn to judge the decision separately from how lucky the result was.",
    },
    {
        "challenge_id": "C164", "bias_id": "B055", "bias": "Moral Luck",
        "statement": "The risky idea that worked made her a genius; the same idea that failed made him careless.",
        "options": ("Hindsight Bias", "Moral Luck", "Survivorship Bias", "Self-serving Bias"),
        "correct": "B", "explanation": "Moral judgment followed the outcome, not just the risk taken.",
        "reflection": "A bold move praised in one person but criticised in another because results differed?",
        "why": "Success and failure are memorable endings, so they can rewrite how brave a choice looked.",
        "context": "Work", "difficulty": "Application",
        "objective": "Learn to evaluate risk-taking by what was known at the time, not only by what happened.",
    },
    {
        "challenge_id": "C165", "bias_id": "B055", "bias": "Moral Luck",
        "statement": "A joke landed well in one room and offended in another — and we judged the teller's character differently each time.",
        "options": ("Hostile Attribution Bias", "Moral Luck", "Horn Effect", "Fundamental Attribution Error"),
        "correct": "B", "explanation": "The same action got different moral weight because outcomes differed.",
        "reflection": "An action you judged more harshly because it happened to go badly?",
        "why": "Harm that actually happened feels more blameworthy than the same gamble that luckily did no harm.",
        "context": "Social situations", "difficulty": "Ambiguous",
        "objective": "Learn to separate intent and risk from the luck of how it landed.",
    },
    # B056 Texas Sharpshooter Fallacy
    {
        "challenge_id": "C166", "bias_id": "B056", "bias": "Texas Sharpshooter Fallacy",
        "statement": "After the fact, we pointed to three wins as proof of our strategy — ignoring all the misses.",
        "options": ("Confirmation Bias", "Texas Sharpshooter Fallacy", "Survivorship Bias", "Clustering Illusion"),
        "correct": "B", "explanation": "The pattern was drawn around the hits after they happened.",
        "reflection": "A success story built by cherry-picking the examples that fit?",
        "why": "Clusters stand out after the fact, and it is easy to pretend we aimed at them from the start.",
        "context": "Work", "difficulty": "Recognition",
        "objective": "Learn to ask what you predicted before the hits, not only what you notice afterward.",
    },
    {
        "challenge_id": "C167", "bias_id": "B056", "bias": "Texas Sharpshooter Fallacy",
        "statement": "All the best cafés seem to be on this street — but we only counted the good ones, not the weak ones nearby.",
        "options": ("Clustering Illusion", "Texas Sharpshooter Fallacy", "Confirmation Bias", "Availability Heuristic"),
        "correct": "B", "explanation": "A target was drawn around the positives after looking around.",
        "reflection": "A pattern you noticed only after choosing where to look?",
        "why": "Once we see a clump, it is tempting to treat that clump as the whole map.",
        "context": "Everyday life", "difficulty": "Application",
        "objective": "Learn to count the misses in the same area before declaring a pattern.",
    },
    {
        "challenge_id": "C168", "bias_id": "B056", "bias": "Texas Sharpshooter Fallacy",
        "statement": "The wellness trend 'works' because we highlight the people who improved and forget everyone who didn't.",
        "options": ("Survivorship Bias", "Texas Sharpshooter Fallacy", "Confirmation Bias", "Pro-Innovation Bias"),
        "correct": "B", "explanation": "Proof was built by circling the winners after the results were known.",
        "reflection": "A trend praised using only the success stories you went looking for?",
        "why": "After results arrive, it is easy to draw a neat circle around the cases that support our belief.",
        "context": "Health", "difficulty": "Ambiguous",
        "objective": "Learn to test claims on the full group, not only the highlighted hits.",
    },
    # B057 Overconfidence Effect
    {
        "challenge_id": "C169", "bias_id": "B057", "bias": "Overconfidence Effect",
        "statement": "I was 90% sure I knew the answer — and I was wrong.",
        "options": ("Dunning-Kruger Effect", "Overconfidence Effect", "Confirmation Bias", "Illusion of Control"),
        "correct": "B", "explanation": "Certainty ran ahead of actual accuracy.",
        "reflection": "A time you felt completely sure and still missed?",
        "why": "Confidence is a feeling, not a scorecard — but it often feels like proof.",
        "context": "Learning", "difficulty": "Recognition",
        "objective": "Learn to treat strong certainty as a signal to double-check, not to stop checking.",
    },
    {
        "challenge_id": "C170", "bias_id": "B057", "bias": "Overconfidence Effect",
        "statement": "We estimated the project would definitely finish early — no one built in serious delay.",
        "options": ("Planning Fallacy", "Overconfidence Effect", "Optimism Bias", "Normalcy Bias"),
        "correct": "B", "explanation": "The team sounded more certain than past results justified.",
        "reflection": "A plan where confidence was high but evidence for it was thin?",
        "why": "Groups can amplify confidence because shared certainty feels reassuring.",
        "context": "Work", "difficulty": "Application",
        "objective": "Learn to ask what could make your confident forecast wrong.",
    },
    {
        "challenge_id": "C171", "bias_id": "B057", "bias": "Overconfidence Effect",
        "statement": "I only studied the questions I was sure about — and was surprised by the ones I 'knew' I'd get right.",
        "options": ("Confirmation Bias", "Overconfidence Effect", "Dunning-Kruger Effect", "Choice-Supportive Bias"),
        "correct": "B", "explanation": "High confidence led to skipping the very areas that needed review.",
        "reflection": "Topics you skipped revising because you already felt certain?",
        "why": "Feeling sure can shut down the extra practice that unsure topics still get.",
        "context": "Learning", "difficulty": "Ambiguous",
        "objective": "Learn to study the questions you feel safest about, not only the shaky ones.",
    },
    # B058 Pro-Innovation Bias
    {
        "challenge_id": "C172", "bias_id": "B058", "bias": "Pro-Innovation Bias",
        "statement": "We bought the shiny new software before asking whether the old system was actually the problem.",
        "options": ("Pro-Innovation Bias", "Status Quo Bias", "Anchoring Bias", "Bandwagon Effect"),
        "correct": "A", "explanation": "Newness itself was treated as a reason to switch.",
        "reflection": "A new tool adopted because it felt modern, not because it solved the issue?",
        "why": "Novel solutions carry hope, and hope can skip the boring step of diagnosing the real problem.",
        "context": "Work", "difficulty": "Recognition",
        "objective": "Learn to ask what problem a new tool solves before buying the promise of new.",
    },
    {
        "challenge_id": "C173", "bias_id": "B058", "bias": "Pro-Innovation Bias",
        "statement": "The hospital rolled out a new app for booking — but the phones worked fine and fewer older patients could use it.",
        "options": ("Pro-Innovation Bias", "Semmelweis Reflex", "Reactance", "Status Quo Bias"),
        "correct": "A", "explanation": "Innovation was assumed helpful before its limits were weighed.",
        "reflection": "A digital change that helped some people but made things harder for others?",
        "why": "New can signal progress so strongly that trade-offs get less attention.",
        "context": "Health", "difficulty": "Application",
        "objective": "Learn to test who benefits and who loses before calling an innovation an upgrade.",
    },
    {
        "challenge_id": "C174", "bias_id": "B058", "bias": "Pro-Innovation Bias",
        "statement": "The school replaced a simple paper form with a complicated portal — because 'it's time to modernise.'",
        "options": ("Pro-Innovation Bias", "Curse of Knowledge", "Reactance", "Planning Fallacy"),
        "correct": "A", "explanation": "Modernising was treated as enough reason, without checking if it helped users.",
        "reflection": "A process made more complex in the name of improvement?",
        "why": "Innovation can feel like leadership, even when the old way was clearer for most people.",
        "context": "Learning", "difficulty": "Ambiguous",
        "objective": "Learn to judge changes by user outcomes, not by how advanced they look.",
    },
    # B059 Semmelweis Reflex
    {
        "challenge_id": "C175", "bias_id": "B059", "bias": "Semmelweis Reflex",
        "statement": "The team dismissed the new safety checklist because 'we've never needed it before.'",
        "options": ("Status Quo Bias", "Semmelweis Reflex", "Normalcy Bias", "Belief Perseverance"),
        "correct": "B", "explanation": "New guidance was rejected because it challenged the old way.",
        "reflection": "A new practice brushed off mainly because it was not how things were done?",
        "why": "Established routines feel tested, so unfamiliar fixes can feel wrong before they are tried.",
        "context": "Work", "difficulty": "Recognition",
        "objective": "Learn to judge new evidence on its merits, not on how long the old way lasted.",
    },
    {
        "challenge_id": "C176", "bias_id": "B059", "bias": "Semmelweis Reflex",
        "statement": "Doctors resisted handwashing at first — the idea clashed too hard with what they already believed.",
        "options": ("Authority Bias", "Semmelweis Reflex", "Confirmation Bias", "Belief Perseverance"),
        "correct": "B", "explanation": "Evidence was rejected because it threatened established practice.",
        "reflection": "A good idea you or others resisted because it upset the usual story?",
        "why": "When new evidence attacks a trusted norm, the norm can fight back harder than the data.",
        "context": "Health", "difficulty": "Application",
        "objective": "Learn to notice when rejection is about identity and tradition, not about the evidence itself.",
    },
    {
        "challenge_id": "C177", "bias_id": "B059", "bias": "Semmelweis Reflex",
        "statement": "The office laughed off the intern's suggestion — then adopted the same idea when a senior manager repeated it.",
        "options": ("Authority Bias", "Semmelweis Reflex", "In-group Bias", "Halo Effect"),
        "correct": "B", "explanation": "The idea was rejected at first because it came from outside the established view.",
        "reflection": "A useful suggestion ignored until someone more senior said it?",
        "why": "New ideas can threaten hierarchy and habit, so they get filtered through who is allowed to challenge norms.",
        "context": "Work", "difficulty": "Ambiguous",
        "objective": "Learn to evaluate suggestions by content, not only by how familiar or senior the source feels.",
    },
    # B060 Risk Compensation
    {
        "challenge_id": "C178", "bias_id": "B060", "bias": "Risk Compensation",
        "statement": "After I got better brakes, I found myself driving faster in the rain.",
        "options": ("Optimism Bias", "Risk Compensation", "Illusion of Control", "Normalcy Bias"),
        "correct": "B", "explanation": "Feeling safer led to taking more risk, partly offsetting the safety gain.",
        "reflection": "A safety upgrade that made you act a bit bolder afterward?",
        "why": "When danger feels lower, we often give some of that margin back through looser behaviour.",
        "context": "Driving", "difficulty": "Recognition",
        "objective": "Learn that feeling safer can quietly increase risk-taking.",
    },
    {
        "challenge_id": "C179", "bias_id": "B060", "bias": "Risk Compensation",
        "statement": "With the helmet on, I took a trickier line on my bike than I would have without it.",
        "options": ("Illusion of Control", "Risk Compensation", "Optimism Bias", "Overconfidence Effect"),
        "correct": "B", "explanation": "Protection made a riskier choice feel more acceptable.",
        "reflection": "Safety gear that made you push a little harder than before?",
        "why": "Extra protection lowers the perceived cost of risk, so we sometimes spend that savings on more risk.",
        "context": "Health", "difficulty": "Application",
        "objective": "Learn to keep habits steady when safety equipment improves, instead of spending the buffer.",
    },
    {
        "challenge_id": "C180", "bias_id": "B060", "bias": "Risk Compensation",
        "statement": "The new handrails made the stairs feel safer — so I started texting while walking down them.",
        "options": ("Illusion of Control", "Risk Compensation", "Normalcy Bias", "Optimism Bias"),
        "correct": "B", "explanation": "Added safety was partly cancelled by paying less attention.",
        "reflection": "A safety feature that made you less careful in another way?",
        "why": "When the environment feels safer, attention can drift — and attention is its own safety layer.",
        "context": "Everyday life", "difficulty": "Ambiguous",
        "objective": "Learn that safety improvements work best when behaviour does not loosen to match.",
    },
]
