"""Bias definitions for Tier 2 (B021–B040)."""

TIER2_BIASES = [
    {
        "bias_id": "B021",
        "name": "Planning Fallacy",
        "definition": "We routinely underestimate how long tasks will take and overestimate how smoothly they will go.",
        "category": "Decision Making",
        "description": "Even with past experience of delays, we often believe this time will be different and plan too optimistically.",
        "everyday_tip": "When estimating time, look at how long similar tasks actually took — not how long you hoped they would take.",
        "common_contexts": "Work, Everyday life, Learning, Health",
        "tier": 2,
    },
    {
        "bias_id": "B022",
        "name": "Recency Bias",
        "definition": "We give more weight to recent events than to older ones, even when the older pattern matters more.",
        "category": "Decision Making",
        "description": "The latest example feels freshest and can overshadow a longer track record of evidence.",
        "everyday_tip": "Before deciding, ask what the full history shows — not just the last week.",
        "common_contexts": "Work, Finance, Relationships, Media",
        "tier": 2,
    },
    {
        "bias_id": "B023",
        "name": "Bandwagon Effect",
        "definition": "We are more likely to adopt a belief or behaviour because many others are doing it.",
        "category": "Social Judgement",
        "description": "Popularity can feel like proof, even when we have not checked the reasons ourselves.",
        "everyday_tip": "Before joining in, ask whether you would still choose this if nobody else were doing it.",
        "common_contexts": "Social Media, Work, Politics, Everyday life",
        "tier": 2,
    },
    {
        "bias_id": "B024",
        "name": "Mere Exposure Effect",
        "definition": "We tend to like things more simply because we have encountered them before.",
        "category": "Social Judgement",
        "description": "Familiarity can create warmth and preference, even without new reasons to prefer something.",
        "everyday_tip": "Notice when you like something mainly because it feels familiar — not because you have compared it fairly.",
        "common_contexts": "Relationships, Media, Work, Everyday life",
        "tier": 2,
    },
    {
        "bias_id": "B025",
        "name": "Endowment Effect",
        "definition": "We value things more highly simply because we already own them.",
        "category": "Finance",
        "description": "Ownership changes how much something feels worth, compared with an identical item we do not own.",
        "everyday_tip": "When selling or keeping something, ask what you would pay for it today if you did not already have it.",
        "common_contexts": "Finance, Everyday life, Work, Negotiation",
        "tier": 2,
    },
    {
        "bias_id": "B026",
        "name": "Gambler's Fallacy",
        "definition": "We expect random events to balance out in the short run, as if past outcomes change future odds.",
        "category": "Decision Making",
        "description": "Independent random events do not 'make up' for earlier results, but it can feel like they should.",
        "everyday_tip": "Ask whether each new event is truly independent — or whether you are expecting a pattern that randomness does not owe you.",
        "common_contexts": "Everyday life, Finance, Sport, Decision Making",
        "tier": 2,
    },
    {
        "bias_id": "B027",
        "name": "Clustering Illusion",
        "definition": "We see meaningful patterns in small sets of random or unrelated events.",
        "category": "Decision Making",
        "description": "A short streak of similar outcomes can feel like a signal, even when it is just noise.",
        "everyday_tip": "Before calling something a pattern, ask how much data you really have.",
        "common_contexts": "Work, Health, Sport, Everyday life",
        "tier": 2,
    },
    {
        "bias_id": "B028",
        "name": "Representativeness Heuristic",
        "definition": "We judge how likely something is by how much it resembles a stereotype, instead of using actual odds.",
        "category": "Decision Making",
        "description": "A good story or familiar type can feel more probable than the base rate suggests.",
        "everyday_tip": "When a description feels like a perfect fit, check the real frequency before deciding.",
        "common_contexts": "Work, Learning, Media, Everyday life",
        "tier": 2,
    },
    {
        "bias_id": "B029",
        "name": "Base Rate Neglect",
        "definition": "We ignore general base-rate information and focus on specific, vivid details instead.",
        "category": "Decision Making",
        "description": "A striking example can overpower the broader statistic about how common something really is.",
        "everyday_tip": "Start with how often something happens in general, then adjust — not the other way around.",
        "common_contexts": "Health, Media, Work, Finance",
        "tier": 2,
    },
    {
        "bias_id": "B030",
        "name": "Peak-End Rule",
        "definition": "We judge an experience mainly by its most intense moment and how it ended, not the whole duration.",
        "category": "Emotion",
        "description": "A strong ending or peak moment can reshape memory more than hours of ordinary experience.",
        "everyday_tip": "When recalling an event, ask what happened in the middle — not only the highlight or the finish.",
        "common_contexts": "Relationships, Health, Work, Everyday life",
        "tier": 2,
    },
    {
        "bias_id": "B031",
        "name": "Choice-Supportive Bias",
        "definition": "After making a choice, we remember the chosen option more favourably and downplay its downsides.",
        "category": "Decision Making",
        "description": "Once we commit, our memory and judgment tilt toward making that choice look wiser.",
        "everyday_tip": "After buying or deciding, ask what you would say to a friend making the same choice fresh today.",
        "common_contexts": "Finance, Relationships, Work, Everyday life",
        "tier": 2,
    },
    {
        "bias_id": "B032",
        "name": "Illusion of Control",
        "definition": "We overestimate how much influence we have over outcomes that are mostly chance or outside our control.",
        "category": "Self-awareness",
        "description": "Small actions can feel like they are steering big results, even when they are not.",
        "everyday_tip": "Ask which parts of the outcome you can actually affect — and which parts are luck or other people.",
        "common_contexts": "Everyday life, Work, Health, Finance",
        "tier": 2,
    },
    {
        "bias_id": "B033",
        "name": "Spotlight Effect",
        "definition": "We overestimate how much other people notice our appearance, mistakes, or behaviour.",
        "category": "Social Judgement",
        "description": "We are each at the centre of our own attention, but others are usually paying far less attention to us.",
        "everyday_tip": "When you feel painfully visible, ask what you would think if a friend did the same thing.",
        "common_contexts": "Work, Relationships, Everyday life, Learning",
        "tier": 2,
    },
    {
        "bias_id": "B034",
        "name": "Cognitive Dissonance",
        "definition": "When our actions clash with our beliefs, we often change our beliefs or excuses rather than face the clash.",
        "category": "Emotion",
        "description": "Mental discomfort pushes us to justify, minimise, or reframe what we did so it fits who we think we are.",
        "everyday_tip": "When you catch yourself rationalising, ask what belief your action is bumping into.",
        "common_contexts": "Health, Relationships, Work, Everyday life",
        "tier": 2,
    },
    {
        "bias_id": "B035",
        "name": "Belief Perseverance",
        "definition": "We keep believing something even after the evidence supporting it has been weakened or removed.",
        "category": "Decision Making",
        "description": "Once a belief takes hold, we can defend it with new reasons after the original reasons fall away.",
        "everyday_tip": "Ask what evidence would change your mind — and whether you are still using it honestly.",
        "common_contexts": "Politics, Work, Relationships, Media",
        "tier": 2,
    },
    {
        "bias_id": "B036",
        "name": "Normalcy Bias",
        "definition": "We underestimate the chance of disruption and assume things will keep going as they usually do.",
        "category": "Decision Making",
        "description": "Familiar routines feel stable, so warnings or unusual signs can be brushed aside too easily.",
        "everyday_tip": "When something feels 'unthinkable,' ask what you would do if it happened anyway.",
        "common_contexts": "Health, Everyday life, Work, Finance",
        "tier": 2,
    },
    {
        "bias_id": "B037",
        "name": "Curse of Knowledge",
        "definition": "Once we know something, we find it hard to imagine not knowing it.",
        "category": "Learning",
        "description": "Experts and experienced people can explain in ways that skip steps obvious to them but not to beginners.",
        "everyday_tip": "When explaining, ask what confused you when you first learned this.",
        "common_contexts": "Work, Learning, Relationships, Everyday life",
        "tier": 2,
    },
    {
        "bias_id": "B038",
        "name": "Illusory Correlation",
        "definition": "We perceive a link between two things when none exists, or see a stronger link than the data supports.",
        "category": "Decision Making",
        "description": "Memorable pairings can feel like cause and effect, especially when we already expect a connection.",
        "everyday_tip": "Before blaming one thing for another, ask how often the effect happens without the cause.",
        "common_contexts": "Health, Everyday life, Work, Relationships",
        "tier": 2,
    },
    {
        "bias_id": "B039",
        "name": "Conjunction Fallacy",
        "definition": "We judge a detailed, specific story as more likely than a broader, more general one.",
        "category": "Decision Making",
        "description": "Extra detail can make a scenario feel more believable, even though specifics always lower the true odds.",
        "everyday_tip": "Ask whether each added detail makes the story more vivid — or actually more probable.",
        "common_contexts": "Media, Work, Learning, Everyday life",
        "tier": 2,
    },
    {
        "bias_id": "B040",
        "name": "Illusory Truth Effect",
        "definition": "Repeated statements feel more true, even when we know we should check them.",
        "category": "Media",
        "description": "Familiar wording creates a sense of accuracy, whether or not the claim has been verified.",
        "everyday_tip": "Treat familiarity as a reason to pause — not as proof something is correct.",
        "common_contexts": "Media, Politics, Social Media, Health",
        "tier": 2,
    },
]
