"""Challenge content for Tier 3 biases B041–B050 (C121–C150)."""

TIER3_CHALLENGES_A = [
    # B041 Actor-Observer Bias
    {
        "challenge_id": "C121", "bias_id": "B041", "bias": "Actor-Observer Bias",
        "statement": "When they're late, I think they're rude. When I'm late, it's because the morning was impossible.",
        "options": ("Fundamental Attribution Error", "Actor-Observer Bias", "Self-serving Bias", "Hostile Attribution Bias"),
        "correct": "B", "explanation": "The same lateness gets a character story for them and a situation story for me.",
        "reflection": "A time you blamed someone's character but blamed circumstances for yourself?",
        "why": "We know our own context from the inside, but only see others from the outside.",
        "context": "Everyday life", "difficulty": "Recognition",
        "objective": "Learn to apply the same kind of explanation to others that you use for yourself.",
    },
    {
        "challenge_id": "C122", "bias_id": "B041", "bias": "Actor-Observer Bias",
        "statement": "My colleague snapped and I called them difficult — but when I snapped, it was stress.",
        "options": ("Hostile Attribution Bias", "Actor-Observer Bias", "Horn Effect", "Negativity Bias"),
        "correct": "B", "explanation": "Their behaviour became a trait; mine became a one-off caused by pressure.",
        "reflection": "When have you labelled someone else's mood as 'who they are' but yours as 'what happened'?",
        "why": "Our own reasons feel vivid and situational, while other people's actions look like personality.",
        "context": "Work", "difficulty": "Application",
        "objective": "Learn to ask what pressure might explain someone else's behaviour before naming their character.",
    },
    {
        "challenge_id": "C123", "bias_id": "B041", "bias": "Actor-Observer Bias",
        "statement": "He failed the test because he's lazy, I failed because the questions were unfair.",
        "options": ("Self-serving Bias", "Actor-Observer Bias", "Fundamental Attribution Error", "Dunning-Kruger Effect"),
        "correct": "B", "explanation": "Failure was explained by character for him and by circumstances for me.",
        "reflection": "A failure you explained with context, but judged someone else's with personality?",
        "why": "Protecting our self-image and knowing our own story makes double standards easy to miss.",
        "context": "Learning", "difficulty": "Ambiguous",
        "objective": "Learn to compare how you explain your outcomes with how you explain others' outcomes.",
    },
    # B042 Bias Blind Spot
    {
        "challenge_id": "C124", "bias_id": "B042", "bias": "Bias Blind Spot",
        "statement": "My friends are so confirmation-biased — I, on the other hand, just look at facts.",
        "options": ("Naive Realism", "Bias Blind Spot", "False Consensus Effect", "Self-serving Bias"),
        "correct": "B", "explanation": "Bias was easy to see in others and invisible in myself.",
        "reflection": "A bias you notice quickly in others but rarely in yourself?",
        "why": "Biases feel like clear distortions in other people and like common sense in us.",
        "context": "Everyday life", "difficulty": "Recognition",
        "objective": "Learn that spotting bias in others does not mean you are free of it.",
    },
    {
        "challenge_id": "C125", "bias_id": "B042", "bias": "Bias Blind Spot",
        "statement": "Everyone at the meeting was being political — except me, I was just being honest.",
        "options": ("Naive Realism", "In-group Bias", "Bias Blind Spot", "Self-serving Bias"),
        "correct": "C", "explanation": "Motives were assigned to others while my own view felt neutral.",
        "reflection": "When have you felt like the one objective person in a heated room?",
        "why": "Our own motives feel clear and justified from the inside, so they do not look like bias.",
        "context": "Work", "difficulty": "Application",
        "objective": "Learn to ask what your own interests might be colouring, not only other people's.",
    },
    {
        "challenge_id": "C126", "bias_id": "B042", "bias": "Bias Blind Spot",
        "statement": "I can list five biases my partner has — but struggle to name one I might share.",
        "options": ("Bias Blind Spot", "Fundamental Attribution Error", "False Consensus Effect", "Dunning-Kruger Effect"),
        "correct": "A", "explanation": "Bias detection worked better outward than inward.",
        "reflection": "Could you name a bias you have shown this month, not just one you've noticed in others?",
        "why": "Bias is easier to spot at a distance, especially when it is not threatening our self-image.",
        "context": "Relationships", "difficulty": "Ambiguous",
        "objective": "Learn to turn bias-spotting inward with the same energy you use on others.",
    },
    # B043 Naive Realism
    {
        "challenge_id": "C127", "bias_id": "B043", "bias": "Naive Realism",
        "statement": "I don't get how anyone could watch that and not see the obvious truth.",
        "options": ("False Consensus Effect", "Naive Realism", "Confirmation Bias", "In-group Bias"),
        "correct": "B", "explanation": "My view felt like plain reality, not one perspective among many.",
        "reflection": "A disagreement where you felt the other side must be ignoring obvious facts?",
        "why": "Our own experience feels direct, so different views can seem irrational instead of different.",
        "context": "Politics", "difficulty": "Recognition",
        "objective": "Learn that your view can feel like reality itself while still being a perspective.",
    },
    {
        "challenge_id": "C128", "bias_id": "B043", "bias": "Naive Realism",
        "statement": "If people were thinking clearly, they'd agree with me on this — disagreement means they're biased.",
        "options": ("Bias Blind Spot", "Naive Realism", "Authority Bias", "Just-World Hypothesis"),
        "correct": "B", "explanation": "Agreement was treated as the mark of clear thinking.",
        "reflection": "When have you assumed disagreement meant the other person was not reasoning properly?",
        "why": "We experience our conclusions as clear sight, so conflict can feel like someone else's distortion.",
        "context": "Work", "difficulty": "Application",
        "objective": "Learn to treat disagreement as a clue about different information or values, not only bad thinking.",
    },
    {
        "challenge_id": "C129", "bias_id": "B043", "bias": "Naive Realism",
        "statement": "The facts are right in front of us — I don't see how there are two sides to this.",
        "options": ("Confirmation Bias", "Naive Realism", "Anchoring Bias", "Framing Effect"),
        "correct": "B", "explanation": "One interpretation was mistaken for the only reasonable reading of the facts.",
        "reflection": "An issue where you felt the answer was plain, but others sincerely saw it differently?",
        "why": "When evidence fits our view neatly, it is easy to forget that others may weigh it differently.",
        "context": "Media", "difficulty": "Ambiguous",
        "objective": "Learn to ask what the other side is seeing, not only why they are 'wrong.'",
    },
    # B044 Just-World Hypothesis
    {
        "challenge_id": "C130", "bias_id": "B044", "bias": "Just-World Hypothesis",
        "statement": "After the theft, people asked what he did to make himself a target — instead of blaming the thief.",
        "options": ("Hostile Attribution Bias", "Just-World Hypothesis", "Fundamental Attribution Error", "Horn Effect"),
        "correct": "B", "explanation": "The victim was searched for a reason the bad outcome 'made sense.'",
        "reflection": "A bad event where people looked for what the person 'did wrong' to deserve it?",
        "why": "A fair-world story is comforting, so we sometimes rewrite victims into causes.",
        "context": "Media", "difficulty": "Recognition",
        "objective": "Learn to notice when you are searching for desert instead of looking at harm.",
    },
    {
        "challenge_id": "C131", "bias_id": "B044", "bias": "Just-World Hypothesis",
        "statement": "She got laid off, and I caught myself thinking she must not have worked hard enough.",
        "options": ("Self-serving Bias", "Just-World Hypothesis", "Hindsight Bias", "Survivorship Bias"),
        "correct": "B", "explanation": "A painful outcome was explained as something earned rather than unlucky.",
        "reflection": "When have you quietly assumed someone's misfortune reflected their effort or character?",
        "why": "Believing the world is fair can push us to blame people for outcomes luck also shapes.",
        "context": "Work", "difficulty": "Application",
        "objective": "Learn to separate outcomes from moral judgments about who deserved them.",
    },
    {
        "challenge_id": "C132", "bias_id": "B044", "bias": "Just-World Hypothesis",
        "statement": "The successful neighbour 'must have earned it' — the struggling one 'must have made bad choices.'",
        "options": ("Halo Effect", "Just-World Hypothesis", "Survivorship Bias", "In-group Bias"),
        "correct": "B", "explanation": "Success and struggle were both turned into moral stories.",
        "reflection": "Do you explain other people's luck with effort stories more than your own?",
        "why": "A tidy moral universe feels safer than one where chance plays a big role.",
        "context": "Everyday life", "difficulty": "Ambiguous",
        "objective": "Learn to leave room for luck and context when judging other people's outcomes.",
    },
    # B045 Hostile Attribution Bias
    {
        "challenge_id": "C133", "bias_id": "B045", "bias": "Hostile Attribution Bias",
        "statement": "Their short email felt deliberately cold — though they might just have been busy.",
        "options": ("Negativity Bias", "Hostile Attribution Bias", "Fundamental Attribution Error", "Horn Effect"),
        "correct": "B", "explanation": "Ambiguous tone was read as intentional hostility.",
        "reflection": "A brief message you interpreted as rude before checking what was going on?",
        "why": "When intent is unclear, threat detection can fill the gap with a negative story.",
        "context": "Work", "difficulty": "Recognition",
        "objective": "Learn to ask for neutral explanations before assuming someone meant harm.",
    },
    {
        "challenge_id": "C134", "bias_id": "B045", "bias": "Hostile Attribution Bias",
        "statement": "A friend didn't reply for a day, so I decided they were annoyed with me.",
        "options": ("Spotlight Effect", "Hostile Attribution Bias", "Recency Bias", "Negativity Bias"),
        "correct": "B", "explanation": "Silence was treated as intentional negative intent.",
        "reflection": "When have you read hurt feelings into a delay that had nothing to do with you?",
        "why": "Social uncertainty is uncomfortable, and a clear negative reason can feel easier than not knowing.",
        "context": "Relationships", "difficulty": "Application",
        "objective": "Learn to treat silence or ambiguity as unclear, not automatically hostile.",
    },
    {
        "challenge_id": "C135", "bias_id": "B045", "bias": "Hostile Attribution Bias",
        "statement": "Someone bumped me in the shop and I assumed they did it on purpose — they were just distracted.",
        "options": ("Fundamental Attribution Error", "Hostile Attribution Bias", "Actor-Observer Bias", "Negativity Bias"),
        "correct": "B", "explanation": "A small accident was read as deliberate aggression.",
        "reflection": "A minor bump or glance you took as intentional when it probably was not?",
        "why": "Under uncertainty, our threat radar can upgrade accidents into insults.",
        "context": "Everyday life", "difficulty": "Ambiguous",
        "objective": "Learn to default to accident or distraction before assuming hostile intent.",
    },
    # B046 Egocentric Bias
    {
        "challenge_id": "C136", "bias_id": "B046", "bias": "Egocentric Bias",
        "statement": "Looking back, I remember doing most of the group project — my teammates remember differently.",
        "options": ("Self-serving Bias", "Egocentric Bias", "False Consensus Effect", "Dunning-Kruger Effect"),
        "correct": "B", "explanation": "My own contribution loomed larger in memory than it did for others.",
        "reflection": "A shared task where you remember carrying more than others say you did?",
        "why": "We live through our own effort in detail, so it naturally feels bigger in recall.",
        "context": "Work", "difficulty": "Recognition",
        "objective": "Learn to compare your memory of effort with other people's accounts.",
    },
    {
        "challenge_id": "C137", "bias_id": "B046", "bias": "Egocentric Bias",
        "statement": "I tell the story like I saved the day — though three people handled the crisis together.",
        "options": ("Egocentric Bias", "Self-serving Bias", "Hindsight Bias", "Availability Heuristic"),
        "correct": "A", "explanation": "My role grew in the retelling compared with the shared reality.",
        "reflection": "A group win you later described as mostly your doing?",
        "why": "Our own actions are vivid and central to us, so memory can quietly promote us to lead role.",
        "context": "Work", "difficulty": "Application",
        "objective": "Learn to check whether your story gives others the share they actually had.",
    },
    {
        "challenge_id": "C138", "bias_id": "B046", "bias": "Egocentric Bias",
        "statement": "Years later I still remember my line in the school play more than anyone else's.",
        "options": ("Spotlight Effect", "Egocentric Bias", "Peak-End Rule", "Mere Exposure Effect"),
        "correct": "B", "explanation": "Personal involvement made my part the main memory.",
        "reflection": "A shared event you mostly remember through your own part in it?",
        "why": "What we personally did or said is stored more richly than what others did around us.",
        "context": "Learning", "difficulty": "Ambiguous",
        "objective": "Learn that shared memories are often self-centred even when they feel objective.",
    },
    # B047 Illusion of Transparency
    {
        "challenge_id": "C139", "bias_id": "B047", "bias": "Illusion of Transparency",
        "statement": "I was nervous giving the toast and felt everyone could tell — they said they had no idea.",
        "options": ("Spotlight Effect", "Illusion of Transparency", "Bias Blind Spot", "Negativity Bias"),
        "correct": "B", "explanation": "Inner anxiety felt obvious outside, but it was mostly hidden.",
        "reflection": "A feeling you were sure showed on your face, but nobody noticed?",
        "why": "We feel our emotions strongly from the inside, so we overestimate how visible they are outside.",
        "context": "Relationships", "difficulty": "Recognition",
        "objective": "Learn that inner feelings are usually less readable than they seem.",
    },
    {
        "challenge_id": "C140", "bias_id": "B047", "bias": "Illusion of Transparency",
        "statement": "I thought my disappointment was obvious in the meeting, so I didn't say anything — and my manager was surprised when I brought it up later.",
        "options": ("Illusion of Transparency", "Spotlight Effect", "Reactance", "Hostile Attribution Bias"),
        "correct": "A", "explanation": "I assumed my mood was showing clearly when it was not.",
        "reflection": "A time you stayed quiet because you thought people already knew how you felt?",
        "why": "Because we feel our state so clearly, we expect others can read it without words.",
        "context": "Work", "difficulty": "Application",
        "objective": "Learn to say important feelings out loud instead of assuming they are visible.",
    },
    {
        "challenge_id": "C141", "bias_id": "B047", "bias": "Illusion of Transparency",
        "statement": "During the argument I was sure my hurt was written all over me — my partner said I looked calm.",
        "options": ("Illusion of Transparency", "Spotlight Effect", "Hostile Attribution Bias", "Negativity Bias"),
        "correct": "A", "explanation": "Emotional intensity inside did not match how I appeared outside.",
        "reflection": "An emotion that felt unmistakable to you but invisible to someone else?",
        "why": "Inner experience is loud to us and often quiet to observers.",
        "context": "Relationships", "difficulty": "Ambiguous",
        "objective": "Learn not to rely on appearance alone as proof others understand your state.",
    },
    # B048 Hyperbolic Discounting
    {
        "challenge_id": "C142", "bias_id": "B048", "bias": "Hyperbolic Discounting",
        "statement": "I'd rather have £40 today than £60 in a month — even though I know waiting is better.",
        "options": ("Loss Aversion", "Hyperbolic Discounting", "Anchoring Bias", "Endowment Effect"),
        "correct": "B", "explanation": "The immediate amount pulled harder than the larger later one.",
        "reflection": "A time you chose the sooner smaller reward over the better later one?",
        "why": "Right now feels real and urgent, while later gains feel abstract and easy to discount.",
        "context": "Finance", "difficulty": "Recognition",
        "objective": "Learn to notice when immediacy is overweighting a better delayed option.",
    },
    {
        "challenge_id": "C143", "bias_id": "B048", "bias": "Hyperbolic Discounting",
        "statement": "I planned to save this month's bonus, but once it arrived I spent half on things I didn't need.",
        "options": ("Hyperbolic Discounting", "Sunk Cost Fallacy", "Loss Aversion", "Optimism Bias"),
        "correct": "A", "explanation": "Having money now felt more compelling than the future plan.",
        "reflection": "Money you intended to save but spent once it was actually in your account?",
        "why": "Future goals are easy in theory; present temptation is concrete and immediate.",
        "context": "Finance", "difficulty": "Application",
        "objective": "Learn to protect future-you with rules made before the money arrives.",
    },
    {
        "challenge_id": "C144", "bias_id": "B048", "bias": "Hyperbolic Discounting",
        "statement": "I'll start the diet Monday — but when Monday comes, today's biscuit still wins.",
        "options": ("Restraint Bias", "Hyperbolic Discounting", "Planning Fallacy", "Cognitive Dissonance"),
        "correct": "B", "explanation": "Future discipline felt easy to promise, but present reward won.",
        "reflection": "A plan you made for later that collapsed when later became now?",
        "why": "Tomorrow's willpower feels strong from today, but today has the biscuit in front of us.",
        "context": "Health", "difficulty": "Ambiguous",
        "objective": "Learn that intentions about the future often underestimate present temptation.",
    },
    # B049 Ambiguity Effect
    {
        "challenge_id": "C145", "bias_id": "B049", "bias": "Ambiguity Effect",
        "statement": "I picked the plan with clear costs, even though the flexible one might have saved money.",
        "options": ("Status Quo Bias", "Ambiguity Effect", "Loss Aversion", "Anchoring Bias"),
        "correct": "B", "explanation": "Known terms felt safer than uncertain possible savings.",
        "reflection": "A time you chose the clearer option because the unknown felt too risky?",
        "why": "Not knowing the odds can feel worse than a middling but known outcome.",
        "context": "Finance", "difficulty": "Recognition",
        "objective": "Learn to compare unknown options fairly instead of avoiding them by default.",
    },
    {
        "challenge_id": "C146", "bias_id": "B049", "bias": "Ambiguity Effect",
        "statement": "The job with a clear role description appealed more than one with vague 'lots of opportunity.'",
        "options": ("Ambiguity Effect", "Status Quo Bias", "Optimism Bias", "Framing Effect"),
        "correct": "A", "explanation": "Clarity felt safer than an undefined upside.",
        "reflection": "Have you preferred a clear path over a vague one, even when the vague one might be better?",
        "why": "Ambiguity makes outcomes hard to picture, so clear options get an unfair comfort bonus.",
        "context": "Work", "difficulty": "Application",
        "objective": "Learn to ask what the unclear option might be worth before rejecting it for vagueness alone.",
    },
    {
        "challenge_id": "C147", "bias_id": "B049", "bias": "Ambiguity Effect",
        "statement": "I skipped the new treatment because the side effects weren't fully known — and stuck with the older one I understood.",
        "options": ("Normalcy Bias", "Ambiguity Effect", "Authority Bias", "Status Quo Bias"),
        "correct": "B", "explanation": "Unknown risks pushed the choice toward the familiar option.",
        "reflection": "A decision where missing information made you stick with the known choice?",
        "why": "What we cannot measure feels like a bigger threat than risks we have learned to live with.",
        "context": "Health", "difficulty": "Ambiguous",
        "objective": "Learn to weigh unknowns carefully without treating all ambiguity as worse than known harm.",
    },
    # B050 Identifiable Victim Effect
    {
        "challenge_id": "C148", "bias_id": "B050", "bias": "Identifiable Victim Effect",
        "statement": "One child's story on the news moved me to donate — statistics about thousands hadn't.",
        "options": ("Identifiable Victim Effect", "Availability Heuristic", "Framing Effect", "Negativity Bias"),
        "correct": "A", "explanation": "One named story stirred action more than large numbers did.",
        "reflection": "A single story that moved you more than a bigger statistic about the same issue?",
        "why": "A face and a name make suffering feel real; numbers can stay abstract.",
        "context": "Media", "difficulty": "Recognition",
        "objective": "Learn that one vivid story can outweigh larger but less personal evidence.",
    },
    {
        "challenge_id": "C149", "bias_id": "B050", "bias": "Identifiable Victim Effect",
        "statement": "The office raised money fast for a colleague's sick parent — broader charity drives rarely do as well.",
        "options": ("In-group Bias", "Identifiable Victim Effect", "Mere Exposure Effect", "Bandwagon Effect"),
        "correct": "B", "explanation": "A known person in need sparked more giving than distant causes.",
        "reflection": "When has someone you knew personally received more help than a larger anonymous need?",
        "why": "We respond strongly to people we can picture, especially when they feel close to us.",
        "context": "Work", "difficulty": "Application",
        "objective": "Learn to notice when closeness and identity are driving generosity more than scale of need.",
    },
    {
        "challenge_id": "C150", "bias_id": "B050", "bias": "Identifiable Victim Effect",
        "statement": "A campaign with one patient's photo got my attention — the chart with mortality rates did not.",
        "options": ("Framing Effect", "Identifiable Victim Effect", "Availability Heuristic", "Negativity Bias"),
        "correct": "B", "explanation": "One visible person carried the message more than the broader data.",
        "reflection": "Health or charity appeals that worked on you because of one person, not the numbers?",
        "why": "Statistics describe many lives; one story feels like a life we can imagine standing in front of us.",
        "context": "Health", "difficulty": "Ambiguous",
        "objective": "Learn to let statistics matter even when one story feels more urgent.",
    },
]
