"""Challenge content for Tier 2 biases B031–B040 (C091–C120)."""

TIER2_CHALLENGES_B = [
    # B031 Choice-Supportive Bias
    {
        "challenge_id": "C091", "bias_id": "B031", "bias": "Choice-Supportive Bias",
        "statement": "After buying the car, I kept noticing perks — and forgot the flaws I worried about in the showroom.",
        "options": ("Confirmation Bias", "Choice-Supportive Bias", "Endowment Effect", "Sunk Cost Fallacy"),
        "correct": "B", "explanation": "Memory tilted toward making the purchase look smarter after it was made.",
        "reflection": "After a big purchase, did you start defending it more than you questioned it beforehand?",
        "why": "Once we choose, we want to feel we chose well — so the mind edits the story.",
        "context": "Finance", "difficulty": "Recognition",
        "objective": "Learn that post-choice memory often flatters the option you picked.",
    },
    {
        "challenge_id": "C092", "bias_id": "B031", "bias": "Choice-Supportive Bias",
        "statement": "I moved cities and told everyone it was perfect — though I had serious doubts the week before.",
        "options": ("Optimism Bias", "Choice-Supportive Bias", "Cognitive Dissonance", "Belief Perseverance"),
        "correct": "B", "explanation": "The decision was remembered more positively after committing.",
        "reflection": "A choice you talked up more after making it than while deciding?",
        "why": "Public commitment and private doubt do not sit well together, so recall gets rosier.",
        "context": "Everyday life", "difficulty": "Application",
        "objective": "Learn to compare your after-the-fact story with what you felt before deciding.",
    },
    {
        "challenge_id": "C093", "bias_id": "B031", "bias": "Choice-Supportive Bias",
        "statement": "The holiday I picked now feels like the best option — even though the other plans looked just as good.",
        "options": ("Choice-Supportive Bias", "Peak-End Rule", "Mere Exposure Effect", "Confirmation Bias"),
        "correct": "A", "explanation": "The chosen trip is remembered as clearly better than the alternatives.",
        "reflection": "After choosing between good options, did the one you picked suddenly seem obviously best?",
        "why": "Choosing creates ownership, and ownership makes our option feel more justified.",
        "context": "Everyday life", "difficulty": "Ambiguous",
        "objective": "Learn to notice when commitment is upgrading your memory of the chosen option.",
    },
    # B032 Illusion of Control
    {
        "challenge_id": "C094", "bias_id": "B032", "bias": "Illusion of Control",
        "statement": "I pressed refresh three times, convinced it would make the page load faster.",
        "options": ("Illusion of Control", "Gambler's Fallacy", "Optimism Bias", "Clustering Illusion"),
        "correct": "A", "explanation": "A small action was treated as steering an outcome it could not affect.",
        "reflection": "Any small ritual you do that feels like it helps, though it probably does not?",
        "why": "Doing something feels better than waiting helplessly, so action can feel like control.",
        "context": "Everyday life", "difficulty": "Recognition",
        "objective": "Learn to spot when your actions cannot actually change the outcome.",
    },
    {
        "challenge_id": "C095", "bias_id": "B032", "bias": "Illusion of Control",
        "statement": "I picked my own lottery numbers, so they felt more likely to win than a random ticket.",
        "options": ("Gambler's Fallacy", "Illusion of Control", "Representativeness Heuristic", "Optimism Bias"),
        "correct": "B", "explanation": "Personal choice created a false sense of influence over random odds.",
        "reflection": "Have you ever felt more hopeful about a chance because you chose the details yourself?",
        "why": "Choosing numbers ourselves makes the outcome feel connected to us, even when it is not.",
        "context": "Everyday life", "difficulty": "Application",
        "objective": "Learn that personal involvement does not change random odds.",
    },
    {
        "challenge_id": "C096", "bias_id": "B032", "bias": "Illusion of Control",
        "statement": "When my team is losing, I change seats — as if where I sit could affect the score.",
        "options": ("Optimism Bias", "Illusion of Control", "Bandwagon Effect", "Recency Bias"),
        "correct": "B", "explanation": "A personal action was linked to a result it cannot control.",
        "reflection": "Any lucky routine you keep during games or stressful moments?",
        "why": "In uncertain moments, we reach for anything that might give us a handle on the result.",
        "context": "Sport", "difficulty": "Ambiguous",
        "objective": "Learn to notice comfort rituals that feel like control but are not.",
    },
    # B033 Spotlight Effect
    {
        "challenge_id": "C097", "bias_id": "B033", "bias": "Spotlight Effect",
        "statement": "I spilled coffee on my shirt and felt everyone stared — but nobody mentioned it all day.",
        "options": ("Negativity Bias", "Spotlight Effect", "Illusion of Transparency", "Hostile Attribution Bias"),
        "correct": "B", "explanation": "The mistake felt highly visible, though others barely noticed.",
        "reflection": "A small embarrassment that felt huge to you but probably passed unnoticed?",
        "why": "We live inside our own attention, so our flaws feel giant while others stay focused on themselves.",
        "context": "Work", "difficulty": "Recognition",
        "objective": "Learn that others usually notice your slip-ups far less than you do.",
    },
    {
        "challenge_id": "C098", "bias_id": "B033", "bias": "Spotlight Effect",
        "statement": "I thought my bad haircut was obvious to everyone — my friends said they hadn't noticed.",
        "options": ("Spotlight Effect", "Negativity Bias", "Horn Effect", "Illusion of Transparency"),
        "correct": "A", "explanation": "A personal worry felt public, though it was mostly private.",
        "reflection": "Something about your appearance that felt glaring, but others barely saw?",
        "why": "What bothers us about ourselves takes centre stage in our mind, not in everyone else's.",
        "context": "Everyday life", "difficulty": "Application",
        "objective": "Learn to test your visibility fears against what others actually report noticing.",
    },
    {
        "challenge_id": "C099", "bias_id": "B033", "bias": "Spotlight Effect",
        "statement": "I stumbled over one word in a talk and replayed it for days — the audience moved on in seconds.",
        "options": ("Negativity Bias", "Spotlight Effect", "Peak-End Rule", "Recency Bias"),
        "correct": "B", "explanation": "One slip felt unforgettable to the speaker, but not to listeners.",
        "reflection": "A minor mistake you magnified more than anyone else did?",
        "why": "We are each the star of our own show, so our blunders get a close-up in memory.",
        "context": "Work", "difficulty": "Ambiguous",
        "objective": "Learn that audiences usually weight your whole message, not one wobble.",
    },
    # B034 Cognitive Dissonance
    {
        "challenge_id": "C100", "bias_id": "B034", "bias": "Cognitive Dissonance",
        "statement": "I said I'd cut back on sugar — then told myself one biscuit 'doesn't count' after a hard day.",
        "options": ("Self-serving Bias", "Cognitive Dissonance", "Restraint Bias", "Optimism Bias"),
        "correct": "B", "explanation": "The action clashed with the goal, so the rule got quietly rewritten.",
        "reflection": "A promise to yourself that you explained away when you broke it?",
        "why": "When behaviour and beliefs collide, it is often easier to adjust the story than change the habit.",
        "context": "Health", "difficulty": "Recognition",
        "objective": "Learn to notice when you are reframing a rule to match what you already did.",
    },
    {
        "challenge_id": "C101", "bias_id": "B034", "bias": "Cognitive Dissonance",
        "statement": "I spent a lot on a course I rarely use — so I started saying it is 'investing in myself.'",
        "options": ("Sunk Cost Fallacy", "Choice-Supportive Bias", "Cognitive Dissonance", "Confirmation Bias"),
        "correct": "C", "explanation": "A costly choice was reframed to reduce the discomfort of not using it.",
        "reflection": "Something you defended with a new story after realising you were not using it?",
        "why": "We dislike feeling wasteful or inconsistent, so we reshape the meaning of the choice.",
        "context": "Learning", "difficulty": "Application",
        "objective": "Learn to spot when a new justification is easing discomfort, not adding value.",
    },
    {
        "challenge_id": "C102", "bias_id": "B034", "bias": "Cognitive Dissonance",
        "statement": "I know smoking is bad for me, so I focus on the one uncle who smoked and lived to ninety.",
        "options": ("Confirmation Bias", "Cognitive Dissonance", "Availability Heuristic", "Belief Perseverance"),
        "correct": "B", "explanation": "A comforting exception was used to soften the clash between habit and health knowledge.",
        "reflection": "An exception you hold onto when a habit bumps into what you know?",
        "why": "One counterexample can feel like permission when the main belief is uncomfortable to face.",
        "context": "Health", "difficulty": "Ambiguous",
        "objective": "Learn to notice when you are hunting exceptions to reduce mental discomfort.",
    },
    # B035 Belief Perseverance
    {
        "challenge_id": "C103", "bias_id": "B035", "bias": "Belief Perseverance",
        "statement": "Even after the study was debunked, I still believed the original claim.",
        "options": ("Confirmation Bias", "Belief Perseverance", "Illusory Truth Effect", "Authority Bias"),
        "correct": "B", "explanation": "The belief survived after its main support was removed.",
        "reflection": "Something you kept believing after the main reason for it fell apart?",
        "why": "Letting go of a settled belief takes effort, so the mind keeps patching it instead.",
        "context": "Media", "difficulty": "Recognition",
        "objective": "Learn to ask whether you still believe something because the evidence supports it today.",
    },
    {
        "challenge_id": "C104", "bias_id": "B035", "bias": "Belief Perseverance",
        "statement": "My colleague proved the process was fine, but I still felt sure they were the problem.",
        "options": ("Hostile Attribution Bias", "Belief Perseverance", "Confirmation Bias", "Horn Effect"),
        "correct": "B", "explanation": "The original blame stuck even after the explanation changed.",
        "reflection": "When has new information failed to shift a view you already held?",
        "why": "First impressions and early stories can keep running even when the facts move on.",
        "context": "Work", "difficulty": "Application",
        "objective": "Learn to update judgments when the supporting reasons have been overturned.",
    },
    {
        "challenge_id": "C105", "bias_id": "B035", "bias": "Belief Perseverance",
        "statement": "The restaurant got great reviews later, but I still called it bad because of one visit years ago.",
        "options": ("Negativity Bias", "Belief Perseverance", "Anchoring Bias", "Recency Bias"),
        "correct": "B", "explanation": "An old judgment held on after newer evidence improved.",
        "reflection": "A place or person you judged early and never really reconsidered?",
        "why": "Early beliefs become familiar, and familiar beliefs feel true even when life updates.",
        "context": "Everyday life", "difficulty": "Ambiguous",
        "objective": "Learn to reopen old judgments when meaningful new evidence appears.",
    },
    # B036 Normalcy Bias
    {
        "challenge_id": "C106", "bias_id": "B036", "bias": "Normalcy Bias",
        "statement": "Storm warnings came in, but I stayed home because bad weather 'never really hits us here.'",
        "options": ("Optimism Bias", "Normalcy Bias", "Availability Heuristic", "Status Quo Bias"),
        "correct": "B", "explanation": "Past routine made disruption feel unlikely, despite the warning.",
        "reflection": "A warning you downplayed because trouble had not happened locally before?",
        "why": "What has always been normal feels like what will keep being normal, until it does not.",
        "context": "Everyday life", "difficulty": "Recognition",
        "objective": "Learn that a calm history does not guarantee a calm future.",
    },
    {
        "challenge_id": "C107", "bias_id": "B036", "bias": "Normalcy Bias",
        "statement": "The smoke alarm beeped oddly, but I kept cooking because fires 'don't happen to careful people.'",
        "options": ("Normalcy Bias", "Optimism Bias", "Illusion of Control", "Negativity Bias"),
        "correct": "A", "explanation": "Ordinary life felt too normal for a serious risk to feel real.",
        "reflection": "A safety sign or signal you brushed off because the day felt ordinary?",
        "why": "Daily routine is comforting, and comfort can make rare dangers feel unreal.",
        "context": "Everyday life", "difficulty": "Application",
        "objective": "Learn to treat warnings seriously even when your routine has been smooth.",
    },
    {
        "challenge_id": "C108", "bias_id": "B036", "bias": "Normalcy Bias",
        "statement": "People said the company was struggling, but I ignored it — we'd been stable for years.",
        "options": ("Confirmation Bias", "Normalcy Bias", "Sunk Cost Fallacy", "Status Quo Bias"),
        "correct": "B", "explanation": "Long stability made warning signs feel less believable.",
        "reflection": "When has 'it's always been fine' made you slow to react?",
        "why": "A long stretch of normal makes change feel hypothetical, even when signs are showing.",
        "context": "Work", "difficulty": "Ambiguous",
        "objective": "Learn to weigh warning signs even when your own experience has been steady.",
    },
    # B037 Curse of Knowledge
    {
        "challenge_id": "C109", "bias_id": "B037", "bias": "Curse of Knowledge",
        "statement": "I explained the form in two minutes — then watched a new starter get lost on step one.",
        "options": ("Curse of Knowledge", "Dunning-Kruger Effect", "Fundamental Attribution Error", "Naive Realism"),
        "correct": "A", "explanation": "What felt obvious to me skipped steps that were not obvious to a beginner.",
        "reflection": "Something that feels simple to you now but was confusing when you started?",
        "why": "Once we know a thing, it is hard to remember what it was like not to know it.",
        "context": "Work", "difficulty": "Recognition",
        "objective": "Learn to explain from the listener's starting point, not your current one.",
    },
    {
        "challenge_id": "C110", "bias_id": "B037", "bias": "Curse of Knowledge",
        "statement": "My parent kept asking basic phone questions, and I got impatient — forgetting I once needed the same help.",
        "options": ("Fundamental Attribution Error", "Curse of Knowledge", "Horn Effect", "Negativity Bias"),
        "correct": "B", "explanation": "My skill made their struggle feel harder to understand than it should have.",
        "reflection": "When have you forgotten how recently something was new to you too?",
        "why": "Competence can make other people's learning pace feel surprisingly slow.",
        "context": "Relationships", "difficulty": "Application",
        "objective": "Learn to remember your own beginner stage when teaching someone else.",
    },
    {
        "challenge_id": "C111", "bias_id": "B037", "bias": "Curse of Knowledge",
        "statement": "The teacher said the maths was 'obvious' — but half the class was still lost on the first step.",
        "options": ("Authority Bias", "Curse of Knowledge", "Dunning-Kruger Effect", "Overconfidence Effect"),
        "correct": "B", "explanation": "Expert ease made the gap invisible to the person explaining.",
        "reflection": "A teacher or guide who skipped steps that were not obvious to you?",
        "why": "Experts often see the whole path at once, while learners still need the first stones pointed out.",
        "context": "Learning", "difficulty": "Ambiguous",
        "objective": "Learn to test explanations on someone who does not already know the answer.",
    },
    # B038 Illusory Correlation
    {
        "challenge_id": "C112", "bias_id": "B038", "bias": "Illusory Correlation",
        "statement": "Every time I wear this shirt, meetings go well — so now I call it my lucky shirt.",
        "options": ("Illusory Correlation", "Clustering Illusion", "Confirmation Bias", "Illusion of Control"),
        "correct": "A", "explanation": "Two things were linked in memory without evidence they actually connect.",
        "reflection": "A lucky item or routine you linked to success without checking the misses?",
        "why": "Memorable pairings stick, while the times they did not happen together fade away.",
        "context": "Work", "difficulty": "Recognition",
        "objective": "Learn to check how often the effect happens without the supposed cause.",
    },
    {
        "challenge_id": "C113", "bias_id": "B038", "bias": "Illusory Correlation",
        "statement": "I ate sugar and got a headache — so I blamed sugar, ignoring the many sweet days with no headache.",
        "options": ("Availability Heuristic", "Illusory Correlation", "Confirmation Bias", "Base Rate Neglect"),
        "correct": "B", "explanation": "One vivid pairing created a cause link stronger than the data supports.",
        "reflection": "A food or habit you blamed because one memorable day lined up?",
        "why": "When two things happen together once and stand out, our brain files them as partners.",
        "context": "Health", "difficulty": "Application",
        "objective": "Learn to count the non-events before declaring a personal cause.",
    },
    {
        "challenge_id": "C114", "bias_id": "B038", "bias": "Illusory Correlation",
        "statement": "Two rude people had the same accent, so I started expecting rudeness from everyone with it.",
        "options": ("Out-group Homogeneity Bias", "Illusory Correlation", "Representativeness Heuristic", "In-group Bias"),
        "correct": "B", "explanation": "A small memorable pair turned into a broader link without enough evidence.",
        "reflection": "A trait you linked to a group after only a couple of examples?",
        "why": "Striking examples are easy to remember and can feel like a rule after very little data.",
        "context": "Everyday life", "difficulty": "Ambiguous",
        "objective": "Learn to question links built from a few vivid cases.",
    },
    # B039 Conjunction Fallacy
    {
        "challenge_id": "C115", "bias_id": "B039", "bias": "Conjunction Fallacy",
        "statement": "A quiet neighbour who reads poetry feels more likely to be a librarian and a volunteer than just a librarian.",
        "options": ("Representativeness Heuristic", "Conjunction Fallacy", "Base Rate Neglect", "Availability Heuristic"),
        "correct": "B", "explanation": "A richer story felt more likely, even though adding details always lowers the odds.",
        "reflection": "A detailed description that felt more believable because it was more specific?",
        "why": "Specific stories match our imagination better, so they can feel more probable than simpler truths.",
        "context": "Everyday life", "difficulty": "Recognition",
        "objective": "Learn that extra detail can make a story feel more likely while actually making it less likely.",
    },
    {
        "challenge_id": "C116", "bias_id": "B039", "bias": "Conjunction Fallacy",
        "statement": "The email scam with a full backstory felt more real than a plain 'your account is locked' message.",
        "options": ("Illusory Truth Effect", "Conjunction Fallacy", "Authority Bias", "Availability Heuristic"),
        "correct": "B", "explanation": "Added detail made the scam feel more plausible than a simpler version would.",
        "reflection": "When has a detailed story felt more credible just because it was detailed?",
        "why": "Detail creates a vivid picture, and vivid pictures feel like truth.",
        "context": "Media", "difficulty": "Application",
        "objective": "Learn to distrust plausibility that comes from story detail rather than evidence.",
    },
    {
        "challenge_id": "C117", "bias_id": "B039", "bias": "Conjunction Fallacy",
        "statement": "I thought 'late because of traffic and a flat tyre' was more likely than simply 'late because of traffic.'",
        "options": ("Planning Fallacy", "Conjunction Fallacy", "Optimism Bias", "Representativeness Heuristic"),
        "correct": "B", "explanation": "The more specific excuse felt more believable, though it is statistically less likely.",
        "reflection": "A detailed explanation that sounded more convincing because it had more parts?",
        "why": "More pieces can make a story hang together in our minds, even when simpler versions are more common.",
        "context": "Work", "difficulty": "Ambiguous",
        "objective": "Learn that simpler explanations are often more probable than dramatic detailed ones.",
    },
    # B040 Illusory Truth Effect
    {
        "challenge_id": "C118", "bias_id": "B040", "bias": "Illusory Truth Effect",
        "statement": "I'd heard the health claim so many times that it started sounding true — even though I never checked it.",
        "options": ("Confirmation Bias", "Illusory Truth Effect", "Authority Bias", "Availability Heuristic"),
        "correct": "B", "explanation": "Repetition created a feeling of truth without verification.",
        "reflection": "A claim that felt true mostly because you had heard it often?",
        "why": "Familiar phrases are easier to process, and easy can be mistaken for correct.",
        "context": "Health", "difficulty": "Recognition",
        "objective": "Learn that repeated claims need checking, not just familiarity.",
    },
    {
        "challenge_id": "C119", "bias_id": "B040", "bias": "Illusory Truth Effect",
        "statement": "The same rumour kept appearing in my feed, so I began to believe it — no source ever checked out.",
        "options": ("Bandwagon Effect", "Illusory Truth Effect", "Confirmation Bias", "False Consensus Effect"),
        "correct": "B", "explanation": "Seeing it again and again made it feel credible.",
        "reflection": "Something online that felt true because you kept seeing it, not because it was verified?",
        "why": "Repetition builds familiarity, and familiarity quietly borrows the feeling of accuracy.",
        "context": "Social Media", "difficulty": "Application",
        "objective": "Learn to pause when repetition is doing the persuading.",
    },
    {
        "challenge_id": "C120", "bias_id": "B040", "bias": "Illusory Truth Effect",
        "statement": "A catchy slogan from the ad campaign stuck in my head — and later felt like a fact.",
        "options": ("Framing Effect", "Illusory Truth Effect", "Mere Exposure Effect", "Anchoring Bias"),
        "correct": "B", "explanation": "Hearing the line often made it feel factual, not just memorable.",
        "reflection": "An advertising line or slogan that started to feel like common knowledge?",
        "why": "What we hear repeatedly becomes mentally smooth, and smooth can feel true.",
        "context": "Media", "difficulty": "Ambiguous",
        "objective": "Learn to separate memorable wording from verified information.",
    },
]
